### ISSUE TITLE
Doesn't support FormArray?

### ISSUE THREAD

**Issue by denis-productops** [basvandenberg/angular2-select#30]
It appears this may not support FormArray, or is there some way to do it I don't understand?

```
<form [formGroup]="workplanForm">
...
<div formArrayName="workplan_items">
  <div *ngFor="let w of workplanForm.controls.workplan_items.controls; let i=index">
    <div [formGroupName]="i">
      <ng-select formControlName="colleges"
        [options]="colleges_options" multiple="true" placeholder="Select colleges">
      </ng-select>
...
```

```
  ngOnInit() {
    // _fb is a FormBuilder
    this.workplanForm = this._fb.group({
        workplan_items: this._fb.array([
            this._fb.group({
              colleges: ['']
              })
        ])
    });
}
```

When I render the page, I get:

```
error_handler.js:45 EXCEPTION: Error in ./WorkplanComponent class WorkplanComponent - inline template:0:6 caused by: There is no FormControl instance attached to form control element with path: 'workplan_items -> 0 -> colleges'
error_handler.js:47 ORIGINAL EXCEPTION: There is no FormControl instance attached to form control element with path: 'workplan_items -> 0 -> colleges'
error_handler.js:51 Error: There is no FormControl instance attached to form control element with path: 'workplan_items -> 0 -> colleges'
    at _throwError (http://localhost:4200/main.bundle.js:10068:11)
    at _noControlError (http://localhost:4200/main.bundle.js:10055:12)
    at SelectComponent.onChange (http://localhost:4200/main.bundle.js:10041:61)
    at SelectComponent.updateSelection (http://localhost:4200/main.bundle.js:68247:14)
    at SelectComponent.writeValue (http://localhost:4200/main.bundle.js:68292:14)
    at setUpControl (http://localhost:4200/main.bundle.js:10011:23)
    at http://localhost:4200/main.bundle.js:14994:105
    at Array.forEach (native)
    at FormGroupDirective._updateDomValue (http://localhost:4200/main.bundle.js:14989:25)
    at FormGroupDirective.ngOnChanges (http://localhost:4200/main.bundle.js:14924:18)
...
```

**Comment by denis-productops** [comment]
Actually, it was pretty trivial, I just had to change the FormBuilder definition to reflect that it was a multiple select (e.g. use an array):

```
this.workplanForm = this._fb.group({
        workplan_items: this._fb.array([
            this._fb.group({
              colleges: [[]]
              })
        ])
    });
```
